name: Simpleknight
favicon: null
layout_spectrum: 0.9438617755658925
typography_spectrum: 0.7946531039196998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7489905611146241
  lightness: 0.28584745060652494
  saturation: 0.9534694184549153
  rhythmicContrast: 0.9749348941259086
purpose: []
