name: Simpleknight
favicon: null
layout_spectrum: 0.9438617755658925
typography_spectrum: 0.7946531039196998
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "SimpleKnight's Simple Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#070707'
    - '#3D3D3D'
    - '#6F7A77'
    - '#B3BBBE'
  brandStrength: 0.7060932
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.9749348941259086
purpose: []
